FROM dhi.io/httpd:2-debian-dev

ARG HTTP_APACHE2_LOCAL_CONF_DIR
ARG HTTP_APACHE2_SERVER_CONF_DIR
ARG HTTP_APACHE2_LOCAL_CONFD_DIR
ARG HTTP_APACHE2_SERVER_CONFD_DIR
ARG HTTP_APACHE2_SERVER_PORT

COPY ${HTTP_APACHE2_LOCAL_CONF_DIR}/*.conf ${HTTP_APACHE2_SERVER_CONF_DIR}
COPY ${HTTP_APACHE2_LOCAL_CONFD_DIR}/*.conf ${HTTP_APACHE2_SERVER_CONFD_DIR}

EXPOSE ${HTTP_APACHE2_SERVER_PORT}